export const steps = [
  {
    stars: "★",
    title: "FILLING UP THE FORM",
    text: `PLEASE VISIT THE REGISTER BUTTON GIVEN IN EVENTS PAGE WHICH WILL
REDIRECT YOU TO UNSTOP. ON VISITING UNSTOP YOU SHOULD FILL ALL THE REQUIRED
DETAILS WITH ACCURATE INFORMATION BEFORE THE REGISTRATION DEADLINE. KINDLY
MAKE SURE TO SUBMIT THE REQUIRED FEE PAYMENT AS WELL.`
  },
  {
    stars: "★★",
    title: "VERIFYING DETAILS",
    text: `OUR TEAM WILL CONDUCT A THOROUGH VERIFICATION OF THE INFORMATION PROVIDED BY YOU. IF WE ENCOUNTER ANY ISSUES DURING THE VERIFICATION PROCESS, WE WILL CONTACT THE RELEVANT TEAM FOR RESOLUTION. IF EVERYTHING IS IN ORDER, YOU CAN EXPECT TO RECEIVE A CONFIRMATION EMAIL WITHIN 1-2 DAYS.`
  },
  {
    stars: "★★★",
    title: "ENTER THE COSMOS ",
    text: `ONCE YOU RECEIVE THE CONFIRMATION EMAIL, PREPARE TO ROLL OUT AND DOMINATE THE BATTLEFIELD IN FEBRUARY 2025. WELCOME TO THE TRANSFORMERS' REALM, WHERE SPARKS IGNITE, GEARS SHIFT, AND ONLY THE WORTHY CLAIM THE MATRIX OF VICTORY!`
  }
];
