export const steps = [
  {
    stars: "★",
    title: "FILLING UP THE FORM",
    text: `PLEASE VISIT THE REGISTER BUTTON GIVEN IN EVENTS PAGE WHICH WILL
REDIRECT YOU TO UNSTOP. ON VISITING UNSTOP YOU SHOULD FILL ALL THE REQUIRED
DETAILS WITH ACCURATE INFORMATION BEFORE THE REGISTRATION DEADLINE. KINDLY
MAKE SURE TO SUBMIT THE REQUIRED FEE PAYMENT AS WELL.`
  },
  {
    stars: "★★",
    title: "VERIFYING DETAILS",
    text: `PLEASE VISIT THE REGISTER BUTTON GIVEN IN EVENTS PAGE WHICH WILL
REDIRECT YOU TO UNSTOP. ON VISITING UNSTOP YOU SHOULD FILL ALL THE REQUIRED
DETAILS WITH ACCURATE INFORMATION BEFORE THE REGISTRATION DEADLINE. KINDLY
MAKE SURE TO SUBMIT THE REQUIRED FEE PAYMENT AS WELL.`
  },
  {
    stars: "★★★",
    title: "ENTER THE COSMOS OF ROBOTICS",
    text: `PLEASE VISIT THE REGISTER BUTTON GIVEN IN EVENTS PAGE WHICH WILL
REDIRECT YOU TO UNSTOP. ON VISITING UNSTOP YOU SHOULD FILL ALL THE REQUIRED
DETAILS WITH ACCURATE INFORMATION BEFORE THE REGISTRATION DEADLINE. KINDLY
MAKE SURE TO SUBMIT THE REQUIRED FEE PAYMENT AS WELL.`
  }
];
